### ISSUE TITLE
pytest seems to be a missing runtime dependency

### ISSUE THREAD

**Issue by wilderfield** [conda-forge/tvm-py-feedstock#9]
```$ python !$
python relay_quick_start.py
Traceback (most recent call last):
  File "/home/bryanloz/TVM/relay_quick_start.py", line 15, in <module>
    from tvm.relay import testing
  File "/home/bryanloz/anaconda3/envs/tvm/lib/python3.9/site-packages/tvm/relay/testing/__init__.py", line 28, in <module>
    from tvm.testing import enabled_targets
  File "/home/bryanloz/anaconda3/envs/tvm/lib/python3.9/site-packages/tvm/testing.py", line 59, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

Should we add pytest to the runtime dependencies in meta.yml?

**Comment by ngam** [comment]
You can/should add it manually

**Comment by ngam** [comment]
Gonna close this for now, but feel free to reopen or open another issue. I am updating the recipe, so please test again and let me know if things are working well for you.

**Comment by ngam** [comment]
At any rate, I will be adding `pytest` in [bc94606](https://github.com/conda-forge/tvm-py-feedstock/pull/22/commits/bc94606a777e270c5fee5ceadbdce054d8eb504d) (PR #22)
